version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: es-elastic1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      #- esconfig1:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      - esnet
      
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: es-elastic2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      #- esconfig2:/usr/share/elasticsearch/config
    networks:
      - esnet

  elasticsearch-head:
    container_name: es-elastic-head
    image: mobz/elasticsearch-head:5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9100:9100"
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  #esconfig1:
  #  driver: local
  #esconfig2:
  #  driver: local

networks:
  esnet: